name: p
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-257.0.dev <4.0.0"

dependencies:
  adaptive_theme: ^3.2.0
  antdesign_icons: ^0.0.3
  cloud_firestore: ^4.5.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
