// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9qlNgfbJsmordwxrXxB15jHmFpFC6Sc',
    appId: '1:775533939508:web:9ad3e0c56b9d0ace5bb361',
    messagingSenderId: '775533939508',
    projectId: 'yorportfolio-e8627',
    authDomain: 'yorportfolio-e8627.firebaseapp.com',
    storageBucket: 'yorportfolio-e8627.appspot.com',
    measurementId: 'G-ZXY03Z9RXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__Gqb4FIc3IOTLBy37diNPNf9oy6HW-s',
    appId: '1:775533939508:android:5a1fe0f9b2745e625bb361',
    messagingSenderId: '775533939508',
    projectId: 'yorportfolio-e8627',
    storageBucket: 'yorportfolio-e8627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4y_e5s3Mlchy7wWTimo94zxqNVy8oOaM',
    appId: '1:775533939508:ios:442ceb50c87ab55f5bb361',
    messagingSenderId: '775533939508',
    projectId: 'yorportfolio-e8627',
    storageBucket: 'yorportfolio-e8627.appspot.com',
    iosClientId:
        '775533939508-0lln00bmo3cmedk26ef82vgfeg3s3d8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.p',
  );
}
